import React, {useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import usePortfolioMotion from './usePortfolioMotion';
import {ArrowUpRight,ArrowDown,ArrowRight,Sun,Moon,Monitor,Smartphone,Printer,Mail,Phone,Github,Copy,Check,X,MapPin,GraduationCap,Code2,Workflow,Presentation,ExternalLink,MonitorCog} from 'lucide-react';
import {certificates,skills} from './data';
import SplashCursor from './components/SplashCursor';
import FlipCard from './components/FlipCard';
import CertificateImage from './components/CertificateImage';
import Galaxy from './components/Galaxy';
import './styles.css';
import './hero-layout.css';

const readPref=(key,fallback)=>{try{return localStorage.getItem(key)||fallback}catch{return fallback}};
const savePref=(key,value)=>{try{localStorage.setItem(key,value)}catch{}};
function App(){
 const [lang,setLang]=useState(()=>readPref('alastor-lang','zh'));
 const [theme,setTheme]=useState(()=>readPref('alastor-theme','system'));
 const [tab,setTab]=useState('skills'); const [filter,setFilter]=useState('all');
 const [mobile,setMobile]=useState(false); const [selected,setSelected]=useState(null);
 const [copied,setCopied]=useState(false);const [copyError,setCopyError]=useState(false);
 const root=useRef(null);const dialog=useRef(null);const timer=useRef(null);const lastFocus=useRef(null);
 const t=(zh,en)=>lang==='zh'?zh:en;
 useEffect(()=>{document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.title=t('刘好 Alastor — 个人简历','Liu Hao · Alastor — Resume');savePref('alastor-lang',lang)},[lang]);
 useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)');const apply=()=>document.documentElement.dataset.theme=theme==='system'?(media.matches?'dark':'light'):theme;apply();media.addEventListener('change',apply);savePref('alastor-theme',theme);return()=>media.removeEventListener('change',apply)},[theme]);
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 useEffect(()=>{if(selected){lastFocus.current=document.activeElement;dialog.current.showModal();document.body.style.overflow='hidden'}else if(dialog.current?.open){dialog.current.close();document.body.style.overflow='';lastFocus.current?.focus()}return()=>{document.body.style.overflow=''}},[selected]);
 usePortfolioMotion(root,tab,filter);
 const tabs=[['skills',t('专业技能','Skills')],['education',t('教育背景','Education')],['certificates',t('认证与证书','Certificates')]];
 function goTab(value){setTab(value);document.getElementById('details').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
 async function copyWeChat(){try{await navigator.clipboard.writeText('mONESYzdnb');setCopied(true);setCopyError(false);clearTimeout(timer.current);timer.current=setTimeout(()=>setCopied(false),2500)}catch{setCopyError(true)}}
 function tabKeys(event,index){let next;if(event.key==='ArrowRight')next=(index+1)%tabs.length;if(event.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=tabs.length-1;if(next!==undefined){event.preventDefault();setTab(tabs[next][0]);document.getElementById('tab-'+tabs[next][0]).focus()}}
 const themeLabels={system:t('跟随系统','System theme'),light:t('浅色模式','Light theme'),dark:t('深色模式','Dark theme')};
 const ThemeIcon=theme==='system'?MonitorCog:theme==='dark'?Moon:Sun;
 return <div ref={root} className={`site ${mobile?'mobile-preview':''}`}>
  <SplashCursor DYE_RESOLUTION={768} DENSITY_DISSIPATION={2} VELOCITY_DISSIPATION={1.5} PRESSURE={0.15} CURL={4} SPLAT_RADIUS={0.12} COLOR_UPDATE_SPEED={7} RAINBOW_MODE={false} COLOR="#EAB308" />
  <a href="#main" className="skip-link">{t('跳至主要内容','Skip to content')}</a>
  <header className="header"><div className="nav-inner">
   <a href="#" className="brand" aria-label={t('刘好，返回顶部','Liu Hao, back to top')}><span className="brand-mark">刘</span><span>Alastor<span className="brand-dot">.</span></span></a>
   <nav aria-label={t('页面导航','Main navigation')}><a href="#about">{t('关于我','About')}</a><button onClick={()=>goTab('skills')}>{t('能力','Skills')}</button><button onClick={()=>goTab('certificates')}>{t('证书','Certificates')}</button><a href="#contact">{t('联系','Contact')}</a></nav>
   <div className="nav-tools"><button className="icon-button" onClick={()=>setTheme({system:'dark',dark:'light',light:'system'}[theme])} aria-label={`${themeLabels[theme]} · ${t('切换主题','Change theme')}`} title={themeLabels[theme]}><ThemeIcon size={17}/></button><button className="language-button" onClick={()=>setLang(lang==='zh'?'en':'zh')} aria-label={t('Switch to English','切换为中文')}>{lang==='zh'?'EN':'中文'}</button><span className="tool-divider"/><button className="icon-button device-button" onClick={()=>setMobile(!mobile)} aria-pressed={mobile} aria-label={t(mobile?'切换电脑预览':'切换手机预览',mobile?'Desktop preview':'Mobile preview')} title={t('切换设备预览','Toggle device preview')}>{mobile?<Monitor size={17}/>:<Smartphone size={17}/>}</button><button className="print-button" aria-label={t('打印简历','Print CV')} onClick={()=>window.print()}><Printer size={15}/><span>{t('打印简历','Print CV')}</span></button></div>
  </div></header>
  {mobile&&<div className="preview-note">{t('手机预览','Mobile preview')} · <button onClick={()=>setMobile(false)}>{t('退出','Exit')}</button></div>}
  <main id="main">
   <section className="hero" id="about"><div className="hero-galaxy" aria-hidden="true"><Galaxy density={0.7} glowIntensity={0.16} saturation={0} speed={0.35} starSpeed={0.18} rotationSpeed={0.025} twinkleIntensity={0.14} mouseInteraction={false} mouseRepulsion={false} transparent /></div><div className="hero-main">
    <div className="availability hero-reveal"><span/>{t('保持好奇，持续生长','Stay curious. Keep growing.')}<span className="availability-line"/></div>
    <h1 className="hero-reveal"><span className="name-mask"><span className="chinese-name">{t('刘好','Liu Hao')}</span></span><span className="name-mask"><span className="signature">Alastor</span></span><span className="name-seal" aria-hidden="true">{t('求知','知')}</span></h1>
    <div className="hero-school hero-reveal"><GraduationCap size={19}/><span>{t('成都理工大学','Chengdu University of Technology')}</span><i/><span>{t('大一 · 本科在读','First-year undergraduate')}</span></div>
    <h2 className="hero-statement hero-reveal"><span className="statement-line"><span>{t('以数学为底色，','Grounded in mathematics.')}</span></span><span className="statement-line"><span>{t('向数据与智能探索。','Exploring data & intelligence.')}</span></span></h2>
    <p className="hero-description hero-reveal">{t('大数据管理与应用专业在读。擅长逻辑推理与问题拆解，具备 Python 基础与 PPT 制作能力，正在将好奇心转化为扎实的学习与实践。','Studying Big Data Management and Application. A logical thinker with Python fundamentals and presentation skills, turning curiosity into thoughtful learning and practice.')}</p>
    <div className="hero-tags hero-reveal">{[t('数学与逻辑','Math & logic'),'Python',t('信息表达','Visual communication'),t('人工智能探索','Exploring AI')].map(x=><span key={x}>{x}</span>)}</div>
    <div className="hero-actions hero-reveal"><a className="button primary" href="mailto:2445956119@qq.com"><Mail size={17}/>{t('与我联系','Get in touch')}<ArrowUpRight size={17}/></a><a className="github-link" href="https://github.com/m0NESYzdnb" target="_blank" rel="noreferrer"><Github size={18}/>GitHub<ArrowUpRight size={15}/></a></div>
   </div><div className="hero-visual"><div className="opening-curtain" aria-hidden="true"/><img className="hero-background" src={`${import.meta.env.BASE_URL}images/angel-profile.jpg`} alt="" fetchPriority="high"/><div className="hero-visual-caption"><span>ALASTOR</span><span>{t('求知 · 探索 · 生长','LEARN · EXPLORE · GROW')}</span></div><aside className="profile-card-wrap hero-reveal" aria-label={t('个人名片','Personal profile card')}>
    <FlipCard className="profile-flip-card" width={480} height={520} radius={16} tiltMax={7} glareOpacity={0.13} hoverScale={1.015} stiffness={200} damping={25} background="var(--surface)" color="var(--ink)" shadowOpacity={0.24} ariaLabel={t('翻转刘好的个人名片','Flip Liu Hao’s profile card')}
     front={<div className="hero-art profile-front">
    <div className="art-top"><span>ALASTOR / PERSONAL PROFILE</span><span>2026</span></div>
    <div className="orbital" aria-hidden="true"><svg viewBox="0 0 440 420"><defs><radialGradient id="orb"><stop offset="0" stopColor="#c8ad71" stopOpacity=".12"/><stop offset="1" stopColor="#c8ad71" stopOpacity="0"/></radialGradient></defs><circle cx="220" cy="210" r="197" fill="url(#orb)"/><g fill="none" stroke="currentColor"><circle cx="220" cy="210" r="156" opacity=".25"/><circle cx="220" cy="210" r="183" strokeDasharray="2 10" opacity=".32"/><ellipse cx="220" cy="210" rx="181" ry="69" transform="rotate(-38 220 210)" opacity=".6"/><ellipse cx="220" cy="210" rx="181" ry="69" transform="rotate(38 220 210)" opacity=".24"/><path d="M220 9v35m0 331v35M18 210h35m334 0h35" opacity=".4"/></g><circle cx="355" cy="94" r="5" fill="currentColor"/><circle cx="77" cy="306" r="3" fill="currentColor"/></svg><div className="art-character">知<span>{t('学而不止 · 行而不辍','LEARN. EXPLORE. CREATE.')}</span></div><span className="orbit-label">LOGIC × CURIOSITY</span></div>
    <div className="art-bottom"><div><span>{t('专业方向','FIELD OF STUDY')}</span><strong>{t('大数据管理与应用','Big Data Management')}</strong></div><span className="art-arrow"><ArrowUpRight size={24}/></span></div>
   <div className="profile-flip-hint">{t('点击或拖拽，翻阅名片','Click or drag to turn the card')}</div></div>}
     back={<div className="hero-art profile-back"><div className="art-top"><span>ALASTOR / CONTACT CARD</span><span>2026</span></div><div className="profile-back-identity"><span className="profile-monogram" aria-hidden="true">刘</span><h3>{t('刘好','Liu Hao')}<span className="signature">Alastor</span></h3><p>{t('成都理工大学 · 本科在读','Chengdu University of Technology · Undergraduate')}</p><span className="profile-back-field">{t('大数据管理与应用','Big Data Management and Application')}</span></div><dl className="profile-back-contact"><div><dt><Mail size={15}/>{t('邮箱','Email')}</dt><dd>2445956119@qq.com</dd></div><div><dt><Phone size={15}/>{t('电话','Phone')}</dt><dd>166 1286 2893</dd></div><div><dt>{t('微信','WeChat')}</dt><dd>mONESYzdnb</dd></div></dl><div className="art-bottom"><span>{t('中国 · 成都','Chengdu, China')}</span><span className="art-arrow"><ArrowUpRight size={20}/></span></div><div className="profile-flip-hint">{t('再点一下，回到正面','Click again to return')}</div></div>}
    />
   </aside></div><div className="hero-bottom"><span><MapPin size={14}/>{t('中国 · 成都','Chengdu, China')}</span><span>{t('从理解问题，到表达答案。','From understanding a problem to communicating an answer.')}</span><a href="#highlights" aria-label={t('探索更多','Explore more')}><ArrowDown size={17}/></a></div></section>

   <section className="highlights" id="highlights" aria-labelledby="highlights-heading"><div className="highlight-intro"><h2 id="highlights-heading" className="motion-title"><span className="motion-title-inner">{t('学习有迹可循','Learning, documented.')}</span></h2><p>{t('每一份积累，都是下一步的起点。','Every milestone is a new starting point.')}</p></div><div className="stats">{[[15,t('份认证与课程证书','certificates & course credentials')],[7,t('份阿里云专项认证','Alibaba Cloud certifications')],[4,t('项讯飞 AI 技术认证','iFLYTEK AI certifications')]].map(([n,label])=><button key={label} className="stat" onClick={()=>{setFilter(n===7?'cloud':n===4?'iflytek':'all');goTab('certificates')}}><span className="stat-number">{String(n).padStart(2,'0')}<span>↗</span></span><span>{label}</span></button>)}</div></section>

   <section id="details" className="details"><div className="details-header"><h2 className="motion-title"><span className="motion-title-inner">{t('认识我的更多面','A closer look.')}</span></h2><span>{t('能力、经历，以及成长的印记','Skills, education, and steps forward')}</span></div>
    <div className="tabs" role="tablist" aria-label={t('简历内容','Resume sections')}>{tabs.map(([id,label],i)=><button key={id} id={'tab-'+id} role="tab" aria-controls={'panel-'+id} aria-selected={tab===id} tabIndex={tab===id?0:-1} onKeyDown={e=>tabKeys(e,i)} onClick={()=>setTab(id)}>{label}{id==='certificates'&&<span className="count">15</span>}</button>)}</div>
    <div id="panel-skills" role="tabpanel" aria-labelledby="tab-skills" hidden={tab!=='skills'} className="tab-panel skills-panel"><div className="skills-grid">{skills.map((skill,i)=>{const Icon=[Workflow,Code2,Presentation][i];return <article className="skill-card" key={skill.icon}><div className="skill-card-top"><Icon size={25} strokeWidth={1.4}/><span>{skill.level[lang]}</span></div><h3>{skill.title[lang]}</h3><p>{skill.body[lang]}</p><div className="skill-tags">{skill.tags[lang].map(tag=><span key={tag}>{tag}</span>)}</div></article>})}</div><div className="learning-note"><span className="small-star" aria-hidden="true">✳</span><p>{t('正在探索','Currently exploring')}<strong>{t('大模型应用 · 智能体 · RAG','LLM applications · AI agents · RAG')}</strong></p><button onClick={()=>setTab('certificates')}>{t('查看学习认证','View learning credentials')}<ArrowRight size={16}/></button></div></div>
    <div id="panel-education" role="tabpanel" aria-labelledby="tab-education" hidden={tab!=='education'} className="tab-panel education-panel"><div className="education-date">2026.09 <span>— 2030.09</span><small>{t('预计毕业','Expected graduation')}</small></div><article><span className="education-status">{t('本科在读 · 大一','Undergraduate · Year 1')}</span><h3>{t('成都理工大学','Chengdu University of Technology')}</h3><h4>{t('大数据管理与应用','Big Data Management and Application')}</h4><p>{t('以数学学习与逻辑推理为基础，持续构建定量分析、问题建模与技术表达能力。','Building a foundation in quantitative analysis, problem modeling, and technical communication through mathematical learning and logical reasoning.')}</p><div className="education-points"><span>{t('数学基础与定量思维','Mathematics & quantitative thinking')}</span><span>{t('问题分析与结构化表达','Problem analysis & clear communication')}</span></div></article><GraduationCap className="education-art" size={92} strokeWidth={.6}/></div>
    <div id="panel-certificates" role="tabpanel" aria-labelledby="tab-certificates" hidden={tab!=='certificates'} className="tab-panel"><div className="certificate-toolbar"><div className="filters" aria-label={t('证书分类','Certificate filters')}>{[['all',t('全部','All')],['cloud',t('阿里云','Alibaba Cloud')],['iflytek',t('科大讯飞','iFLYTEK')],['python','Python'],['huawei',t('华为','Huawei')]].map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div><span className="certificate-hint">{t('点击证书查看原件','Select a certificate to view')}</span></div><div className="certificate-grid">{certificates.map(cert=>{const visible=filter==='all'||filter==='iflytek'&&cert.id<4||filter==='huawei'&&cert.issuer.en==='Huawei'||cert.category===filter;return <button className={`certificate-card ${visible?'':'filtered-out'}`} key={cert.id} onClick={()=>setSelected(cert)}><div className="certificate-image">{tab==='certificates'&&visible?<CertificateImage key={cert.id} src={cert.image} title={cert.title[lang]} lang={lang}/>:<img src={cert.image} alt={cert.title[lang]} loading="lazy"/>}<span><ExternalLink size={17}/></span></div><div className="certificate-caption"><span>{cert.issuer[lang]}</span><h3>{cert.title[lang]}</h3>{cert.date&&<time>{cert.date.replaceAll('-','.')}</time>}</div></button>})}</div><p className="certificate-disclaimer">{t('依据所提供的证书原件整理。认证与课程结业证明不等同于项目实践经历；详细名称、有效期与颁发主体以原件为准。','Based on the supplied certificate images. Credentials and course completion do not imply project experience. Refer to the originals for exact titles, validity, and issuers.')}</p></div>
   </section>
   <section id="contact" className="contact"><div className="contact-intro"><span className="signature contact-signature">Let's connect.</span><h2 className="motion-title"><span className="motion-title-inner">{t('让下一次交流，成为新的开始。','A conversation could be the next beginning.')}</span></h2><p>{t('欢迎交流学习、研究辅助与数据分析相关机会。','Open to conversations about learning, research support, and data analysis opportunities.')}</p></div><div className="contact-links"><a href="mailto:2445956119@qq.com"><Mail size={18}/><span><small>{t('邮箱','Email')}</small>2445956119@qq.com</span><ArrowUpRight size={18}/></a><a href="tel:16612862893"><Phone size={18}/><span><small>{t('电话','Phone')}</small>166 1286 2893</span><ArrowUpRight size={18}/></a><button onClick={copyWeChat}><span className="wechat-symbol">W</span><span><small>{t('微信','WeChat')}</small>mONESYzdnb</span>{copied?<Check size={17}/>:<Copy size={17}/>}</button><span className="copy-status" role="status">{copied?t('微信号已复制','WeChat ID copied'):copyError?t('请手动复制微信号：mONESYzdnb','Please copy manually: mONESYzdnb'):''}</span></div></section>
  </main><footer><a href="#" className="footer-name">Alastor<span> / {t('刘好','Liu Hao')}</span></a><span>© 2026 {t('刘好','Liu Hao')} · {t('保持热爱，保持探索。','Stay curious, keep exploring.')}</span><span>{t('更新于','Updated')} 2026.10.06</span></footer>
  <dialog ref={dialog} className="certificate-dialog" onCancel={e=>{e.preventDefault();setSelected(null)}} onClick={e=>{if(e.target===dialog.current)setSelected(null)}}><div className="dialog-top"><h2>{selected?.title[lang]}</h2><button className="icon-button" autoFocus onClick={()=>setSelected(null)} aria-label={t('关闭证书','Close certificate')}><X size={22}/></button></div>{selected&&<img src={selected.image} alt={selected.title[lang]}/>}<p>{selected?.issuer[lang]}{selected?.date&&` · ${selected.date}`}</p></dialog>
 </div>
}
const reactRoot = import.meta.hot?.data.reactRoot ?? createRoot(document.getElementById('root'));
if (import.meta.hot) import.meta.hot.data.reactRoot = reactRoot;
reactRoot.render(<React.StrictMode><App/></React.StrictMode>);





